[vim]
any = true

[describe]
any = true
[[describe.args]]
type = "string"
[[describe.args]]
type = "function"

[it]
any = true
[[it.args]]
type = "string"
[[it.args]]
type = "function"

[before_each]
any = true
[[before_each.args]]
type = "function"
[[after_each.args]]
type = "function"

[assert]
any = true

[assert.is_not]
any = true

[[assert.equals.args]]
type = "any"
[[assert.equals.args]]
type = "any"
[[assert.equals.args]]
type = "any"
required = false

[[assert.same.args]]
type = "any"
[[assert.same.args]]
type = "any"
